### ISSUE TITLE
Add descending/ascending cave options?

### ISSUE THREAD

**Issue by navett52** [Captain-Chaos/WorldPainter#18]
Allow people to pick a specific slope/angle and the cave will descend at that rate. Ex. If I pick 45 degrees, the cave layer I am painting will descend at a constant 45 degree angle. Of course I am suggesting constant rates of descent, but I would prefer that over nothing if possible.

**Comment by navett52** [comment]
Or maybe make it to where you can pick a range of angles. So instead of just picking 45 degrees and having the cave descend at that constant rate, you could choose 45-30 degrees and as the cave descends it will randomly pick an angle withing that range as the rate it should descend for a small amount of time, then switch to a different angle.

**Comment by Captain-Chaos** [comment]
Unfortunately there are lots of impossible to answer questions that make this impossible. Descend *from where*? At what level should it start, and at what point? In which direction should it descend? Etc.. It sounds good, but it's not possible to do with a layer which you can paint anywhere and in any shape.

Have you look at the "opposite of terrain" level options? That gives you some control over the slope of the caves, since it will mirror the slope of the terrain above. Of course it does mean you have to have hills or mountains in the right shape above the caves, but that is often appropriate so it can be a good choice.

**Comment by navett52** [comment]
Well I had imagined that it would start at the level you specify when making the cave/tunnels layer. I wasn't sure if it was possible to have it descend following the line you paint. It marks the start point (where you first click) and follows the line having the end point be where you let go of the mouse button, though that does leave some problems if you connect multiple lines of that layer. After I posted this I did explore the 'opposite of terrain' option, and it will work to make interesting enough caves for what I want. My original thought process was just that since you already have tools in the program to measure angles it might not have been so hard to implement. Thank you for reading my issue and responding though, I appreciate that.

**Comment by Captain-Chaos** [comment]
That would be much more complex than the way layers currently work, where they have some effect wherever you paint them, without having to additionally know where you started painting, in which direction you painted, etc...

There are places in WorldPainter where you can specify angles, such as layered custom materials, but those are repeating layers where you don't particularly care where they start, so they start at some arbitrary point.

I think this one is a bit too vague on the one hand and complex on the other, so I hope you don't mind that I close it. If you think of a more concrete way to do something similar feel free to suggest it again!
