### ISSUE TITLE
Annotations are all assumed as one

### ISSUE THREAD

**Issue by Ivain** [Captain-Chaos/WorldPainter#20]
I hate to make a issue report so soon after another has been fixed (the layers work fine with the latest updates), but Annotations have now become somewhat pointless.
Every time I try to use one specific annotation as a mask, it assumes all annotations are the same one. 
The result is that if I import a mask that has more than 1 color of annotation in it, I cannot use it effectively. It fills all annotations at once.
This happens with both global operations and when using a brush.

I'd also like to know if there is anywhere where I can get an older version of WP?

**Comment by Captain-Chaos** [comment]
Could you give some more details? Possibly some concrete steps to reproduce, possibly with the mask image you're using? From your description I'm not entirely sure what you are trying to accomplish and what exactly is going wrong.

**Comment by Ivain** [comment]
I import a RGB image as a mask, select one-to-one (the only option that actually works, has something to do with worldmachine), so it gets imported as annotations. 
I then use a brush or global operations, using 'only on yellow annotations' as a way to select (or any annotation). Then if I click on an area with any sort of annotation, it covers those as well.
So if I have an area with red and yellow annotations, and select to affect only the yellow, it will still affect red

**Comment by Captain-Chaos** [comment]
Alright, I found the bug and I'll fix it in the next release. Thanks for reporting it!

By the way, the reason you can only select "one to one" is that the mask is a colour image, and the other mappings only make sense for scale images. Nothing to do with World Machine. ;-)

**Comment by Ivain** [comment]
I thought it was because if I export a black-and-white image through the bitmap export, it still goes as that. but i guess that technically classifies it as RGB instead of grayscale.

**Comment by Captain-Chaos** [comment]
Possibly. I don't know anything about World Machine. However it is good to keep in mind that just because an image only contains shades of grey, that doesn't make it a grey scale image, it could just be a colour image which happens to contain only grey scales.

A grey scale image has only one channel (brightness), whereas a colour image has multiple colour component channels (for example red, green and blue).

For most purposes in WorldPainter (i.e. pretty much any layer _other_ than Annotations) you would need an actual grey scale image, so you would either have to export it as such, or change the colour image to a grey scale image in a paint program such as GIMP.
