### ISSUE TITLE
Biomes are blotchy after export

### ISSUE THREAD

**Issue by JackIt999** [Captain-Chaos/WorldPainter#209]
For example: a 1-block thin line of a specific biome will export as a dotted line of that biome instead of a solid line. I turned off biome blending to see if that was the culprit, but indeed it was still a broken up line. Its like the biomes were blurred together or something. Exported in the beta 1.15 format

**Comment by MattiBorchers** [comment]
Biomes are stored in 4x4x4 block areas since 1.15. This allows vertical biomes, which are currently not supported by WorldPainter. In addition, you can't export "pixel perfect" biomes in the new map format (only in 1.12).

**Comment by Captain-Chaos** [comment]
Matti is correct. This is a "feature" of Minecraft 1.15+, it does not allow for a higher resolution. Because WorldPainter also still supports Minecraft 1.12 it still allows block-level editing of biomes, but on Exporting to 1.15 format it has no choice but to "round off" every 4x4 block area to the most prevalent biome in that area.

**Comment by darthvader45** [comment]
That's rather annoying visually, as it even seems to be a bit janky in minimap mods.  Hopefully this can be rectified in future versions.
