### ISSUE TITLE
error when installing version 2.8.3, updating to 2.8.3 and openning 2.8.3, the main error is: "Caused by: java.lang.SecurityException: Can't read cryptographic policy directory: unlimited"

### ISSUE THREAD

**Issue by enzoklingu** [Captain-Chaos/WorldPainter#220]
so thats the problem, i unninstalled worldpanter when it couldnt open, when i tried uninstalling and installing again, the error java.lang.ExceptionInInitialize ocurred, and in the log it said Caused by: java.lang.SecurityException: Can't read cryptographic policy directory: unlimited , in the java.plicy i already tried removing the hashtag in front of "crypto.policy=unlimited" but nothing heappenned

**Comment by Captain-Chaos** [comment]
Sorry I never got back to you. In case it's still relevant: this must be a problem with your local Java install. Could it be an old export-restricted version of Java? I would recommend getting rid of every version of Java you can find and installing the latest version.
I'll close this however, since it's not a bug in WorldPainter.
