### ISSUE TITLE
Can't Load World Painter World in 1.18.1 or 1.17.1 Stuck on 0% even after several hours

### ISSUE THREAD

**Issue by HiroWu1** [Captain-Chaos/WorldPainter#224]
I made a world with both worldpainter and worldmachine but after exporting it to minecraft and trying to load in the world in both 1.17.1 and both 1.18.1, but they both stop at 0%, my worldpainter map size isnt the biggest as it is only around 2k by 2k pls help me i am desperate since i have spent several days working on this world.

![Screenshot (20)](https://user-images.githubusercontent.com/92665299/151705594-93baa5c5-e542-4466-8a56-7ffad68a104f.png)

![Screenshot (22)](https://user-images.githubusercontent.com/92665299/151705272-58e4b0f1-0ac7-4158-9353-d8c20cb430fd.png)

**Comment by kientuong114** [comment]
Hi, is your world height 256? I've tried exporting a world that was 320 blocks high, but it wouldn't load, exactly like in your case. However, after changing the world height to 256 it worked. This might not be ideal since your world gen might be higher than that, but at the very least you should be able to get most things working. After loading the world into 1.18 you will get the correct height.

**Comment by Captain-Chaos** [comment]
Minecraft 1.18 is not yet supported by WorldPainter. As the release notes indicate, Minecraft will load maps exported in 1.15 format, but not in the experimental 1.17 format. If this world is not higher than 256 blocks, try exporting it in 1.15 format. If it is higher, you will have to wait for 1.18 support to become available (you will still be able to export this world in that format once it arrives, so you could continue to work on it).
