### ISSUE TITLE
French translation

### ISSUE THREAD

**Issue by Natixe** [Captain-Chaos/WorldPainter#228]
Hello,

I would like to translate your software into French for free because I use it every day and it is very useful so I would like to help your project. I don't ask anything in return, just give me the list of words to translate and I will do it.

Edit: 
Discord Id : Natixe#6286

**Comment by Captain-Chaos** [comment]
Thanks for the offer! WorldPainter is on [Crowdin](https://crowdin.com/project/worldpainter); you can help translate it there, although currently French is already fully done. I am not using the translations yet though, mainly because the strings on there are just a small portion (maybe 5%) of the total text in the program and it is a huge amount of work to extract _all_ the text and make it translatable. I would recommend signing up there and keeping an eye on the project until more text appears (won't be soon!).
