### ISSUE TITLE
Worldborder exporting fails to pre-generate properly.

### ISSUE THREAD

**Issue by Scratchyerik** [Captain-Chaos/WorldPainter#249]
Hello again! (You're pretty based for helping me out with the barrier stuff in such a timely manner saves me a lot of time It's greatly appreciated)

The issue I'm facing is similar to this thread here on Dynmaps Github although seemed to have mentioned its Worldpainter sided and I don't know if its annoying to fix but figured I'd put it here.
https://github.com/webbukkit/dynmap/issues/3104
(Work around doesn't function as its a 1.18 export.

(Attempted also with Chunky and FCP) Essentially the pregenerator seems to be unable to force the chunks to populate the terrain  and only reads the raw terrain from the export. You are required to walk through a piece of land to populate with trees, grass, lava, etc. I have no experience but my assumption would be how the chunk pregen plugins read tiles doesn't enable however worldpainter enforces world population?

I have a live dynmap where you can see the issue at mceurope.ddns.net:8123

Dynmap Screenshot of Issue
![Screenshot 98)](https://user-images.githubusercontent.com/105139393/168454727-7bb3422c-fff7-4c16-ba41-4d3244c4c813.png)

PNG of My Export Settings (Allow minecraft to populate the entire terrain is enabled)
(![export settings](https://user-images.githubusercontent.com/105139393/168454778-d3bfb84b-a0fa-41be-8b27-1cccd2dfdff2.PNG)

**Comment by Captain-Chaos** [comment]
I'm afraid this is not a WorldPainter issue. When you use the Populate layer (or the "allow Minecraft to populate the entire terrain" option), WorldPainter sets the chunk status to `liquid_carvers` instead of `full`, which triggers Minecraft to finish populating the chunk when it first loads it. WorldPainter has no control over what other programs do with that information.
