### ISSUE TITLE
Barrier wall option disables map populating

### ISSUE THREAD

**Issue by Scratchyerik** [Captain-Chaos/WorldPainter#250]
Hello,
Whenever the option to use a Barrier wall is selected instead of a Bedrock wall it disables default populating on export. I believe it has something to do with automatically setting everything past the border as void which disables selection of minecraft settings world type, and it does the same thing when you select "endless" for border. An option or revert to allowing you to choose with a simple barrier wall instead of forcing super flat generation for the void would be appreciated assuming thats how it works.

**Comment by Captain-Chaos** [comment]
Yes, for the endless void the world type needs to be set to Superflat, and unfortunately Minecraft does not populate chunks when that is the world type.

The reason for the endless void is that otherwise Minecraft generates normal land beyond the wall. For bedrock that isn't a problem, but now you can see it so it would look bad and presumably not be what people want or expect.

Maybe I should change the way this works and the barrier option should be another border type, rather than a separate wall choice. That way you could set it to be wide enough so you can't see the other side, without needing to be endless. What do you think?

**Comment by Scratchyerik** [comment]
I think that solution works, I was under the impression that the Bedrock wall stayed intact while you had void border selected. I just tested it.

Which in that case moving the Barrier wall option to the border type is the next best thing.

**Comment by Captain-Chaos** [comment]
Yeah, having the void border behind the bedrock wall would not make much sense since people can't see it or get there anyway. I think I'll do this then. At some point in the future I may make the border options much more flexible, but for now I have to guess at a few options that probably make the most sense to people.

**Comment by Captain-Chaos** [comment]
I've decided to keep the barrier wall option, but make it no longer force the world type to Superflat and no longer generate endless Void. In addition I will add a new barrier border type, which can be used instead and will allow the barrier border to be made much wider so that you cannot see beyond it. This will be in the next release.
