### ISSUE TITLE
scripting, installing custom terrain returns wrong index, ignores parameters

### ISSUE THREAD

**Issue by IR0NSIGHT** [Captain-Chaos/WorldPainter#265]
Im trying to achieve 4 things with a javascript script executed through the worldpaint GUI "run script"
- load custom terrain from file
- install custom terrain
- make terrain show up in "custom terrain" GUI window in worldpaint
- apply custom terrain (without filter for now)

These issues arise:
- the "install to slot x" is ignored. sometime next free slot it chosen,.
- material does not show up in GUI
- returned material index is wrong. it returns the "custom material" index, not the actual Terrain value (as in Terrain.java values[idx])
- no material is actually installed to the returned index, even tho the wp object knows about it at this index

The whole ordeal is very confusing, its hard to even list whats not working.

Instead, ill describe the only way i got it to work somehow:
- calculate actual id for Terrains.values for custom material
- install custom material through GUI so it shows up in GUI
- apply material with actual id

Attaching the script so you can check for yourself.

[custom_terrain.txt](https://github.com/Captain-Chaos/WorldPainter/files/9203261/custom_terrain.txt)

**Comment by IR0NSIGHT** [comment]
edit:
i _think_ the main issues are that installing the custom terrain doesnt work properly, and retrieving actually installed terrains at idx x doesnt either with world.getMixedMaterial(x) (1).
(1) returns terrain as if its properly installed, but when applying the terrain, its the correct custom index, but the terrain is null => pink nothingness

**Comment by Captain-Chaos** [comment]
I agree it's confusing. The issue is that there are two different indices that are involved. One is the custom terrain slot. That's the ordinal of the custom terrain in the list of custom terrains and it runs from 1 to 96. The other is the terrain index. That's the index in the list of _all_ terrains, is zero-based and does not map one to one to custom terrain slots (those are spread out over multiple discontinuous ranges).

You specify the custom terrain slot to `installCustomTerrain.inSlot` (although there is no reason to, and I wouldn't), but what you get back is the terrain index, which is also what you provide to `applyTerrain`.

You don't need that mapping function you created; in fact that is throwing it off. The index returned by `installCustomTerrain` is what you should pass into `applyTerrain`. This will work:

```JavaScript
var terrain = wp.getTerrain()
    .fromFile('C:/Users/Max1M/Documents/Worldpainter/terrain/sandstone_red_yellow.terrain') // The filename of the terrain to load
    .go();

var customTerrainIndex = wp.installCustomTerrain(terrain) // The Custom Terrain to install on the world. See "Loading a Custom Terrain"
    .toWorld(world) // The world on which to install the Custom Terrain. See "Loading a World"
    .go(); // Returns the terrain index to use for actually placing this Custom Terrain using other operations

wp.applyTerrain(customTerrainIndex) // The terrain type index to set
    .toWorld(world) // See "Loading a World" or "Creating a World from a Height Map"
    .go();
```

However, running it in the GUI introduces problems that break this, such as that the new custom terrain is not displayed in the editor, but also that when you save the world, the custom terrains get overwritten. You are better off doing this kind of thing on the command line with the `wpscript` command. Is there a reason why you want it to work in the GUI? I could probably make that work, but that would be non trivial.

**Comment by IR0NSIGHT** [comment]
will investigate further the next couple days, keep issue open until then :)

**Comment by Captain-Chaos** [comment]
I'll close this since I haven't heard from you. Please feel free to open a new issue if you still think there is a bug!
