### ISSUE TITLE
Unsigned Plugins - Follow up to Issue #63

### ISSUE THREAD

**Issue by NoveritaDev** [Captain-Chaos/WorldPainter#284]
I see that there is a relatively well put together interface for the creation of plugins, but given the signing security feature it isn't really viable to distribute custom ones, and it raises the barrier to entry for making them considerably. (I've been fiddling with dependencies for a couple evenings at this point, and still haven't gotten it to work properly.)

I recognize that security is important, but it would be greatly appreciated if there could at least be a config option somewhere so that people can choose to allow unsigned plugins. There are some features that they would be very useful for, mainly regarding underground generation, since the default tools are rather limited.

**Comment by Captain-Chaos** [comment]
That would open the floodgates to people running untrusted code though. There is a reason I implemented that mechanism. I will work with anyone interested to sign their plugin! As long as I can arrange to build it with my own build server, so I can audit the code that is being signed. And I'll also work with you to expand the available API's (although a lot is already possible, such as adding custom tools/operations, layers, custom object formats, etc.).

**Comment by NoveritaDev** [comment]
I understand the risks, it would just be much more convenient to develop for without that check, and would let groups make their own plugins for personal use if they need something niche.

I'm not suggesting removing it entirely, since I do understand the purpose of having it. It would just be useful to have the option to bypass it, be it through a checkbox with a large warning about the risks, or a config file somewhere. As long as people are willing to acknowledge the risks, I don't see the harm in letting them do it.

**Comment by Captain-Chaos** [comment]
Yeah but you know how easy it is to social engineer that. This is how people's Minecraft accounts get hacked. "Never mind that warning, just click yes," especially for the young people who play Minecraft. I'll never drop this requirement from anything that is distributed with my code signing signature.

If you want to make useful things as plugins I'd far prefer that you distribute them publicly of course, and I'll try to make that as easy as possible. That includes setting up a local development environment, which should not be that hard. You are aware of [this](https://www.worldpainter.net/trac/wiki/BuildingWorldPainter) page? Let me know if there are any problems with that page or how I could improve it.

I don't mind if a plugin is niche, and there is no obligation for it to be public. Once the build and signing process is set up it is automatic; I don't audit every commit or something like that. I do that on an ad hoc basis; it's more about traceability and accountability.

When developing a plugin locally like that, WorldPainter would load it from the classpath and there would be no need to disable signature checking. But you could still easily disable the signature check in your local development copy of WorldPainter for testing.

Alternatively, groups who need niche functionality could relatively easily create their own fork of WorldPainter and just modify it directly. That would not be that much more work for the experienced developer who would otherwise be creating that plugin. I hope people wouldn't do that for functionality which would be useful to others though.

**Comment by Captain-Chaos** [comment]
I'll close this since I didn't hear back from you. Don't hesitate to contact me about getting a development environment up and running and/or getting a plugin signed.
