### ISSUE TITLE
Allow unlimited amount of custom materials

### ISSUE THREAD

**Issue by frogocomics** [Captain-Chaos/WorldPainter#29]
I don't understand why the current custom material system is hardcoded, where a collection storing custom materials could just be used instead. This could allow for unlimited terrain types. (Although rare) Some terraforrmers might not have enough slots for all their custom terrain, so I think its better to change the custom materials to a list. (or a collection)

**Comment by Captain-Chaos** [comment]
It's because the terrain type is stored as an 8-bit integer. Each terrain type, including the custom terrain types, has to be mapped onto one of those 256 values, so you can't have unlimited custom terrain types, and it's prudent not to map all the values, to leave room for new built-in terrain types for new Minecraft versions.

If there is demand for it I could certainly add more custom terrain types. Please let me know if that is the case! However since this issue is specifically about unlimited custom terrain types, which isn't possible, I'm going to close this issue.

**Comment by Captain-Chaos** [comment]
(Note that you can still comment on closed issues, so if you have additional questions or comments feel free to add them.)

**Comment by frogocomics** [comment]
Could you make more slots for terrain?

**Comment by Captain-Chaos** [comment]
Are you sure you need that many custom terrain types? There are other ways of replacing the terrain with a custom material, for example Custom Ground Cover layers with a negative thickness (which makes them dig down into the terrain instead of lie on top of it), which might even be more suitable in some circumstances (for example it allows you more control over the depth, and the shape of the edges).

**Comment by frogocomics** [comment]
It's simpler just using terrain types, since my new coloring method uses stored colortables (terrain files). Could you either double the possible amounts of terrain or make an option to do so?

**Comment by Captain-Chaos** [comment]
Making it an option isn't possible. If I allocate those terrain ids to extra custom terrain slots I can't ever use them for something else. That's why I'm hesitant to add more custom terrain types. There are 48 slots now, which is already quite a lot, and so far you're the only one asking for more. Why do you need so many?

**Comment by frogocomics** [comment]
My gradient coloration method needs lots of custom terrains. Just stone used 24 materials

**Comment by Captain-Chaos** [comment]
Alright, well I'll add more custom terrain types. Could you create a separate feature request for that, so i can track it? It may be a while because I also want to change the mechanism by which you add custom terrain types from a huge grid of buttons to a + button with which you can add new custom terrain types, like for layers or custom biomes (while still being backed by a fixed number of slots so there will still be a maximum amount).
