### ISSUE TITLE
[Feature request] Add American English

### ISSUE THREAD

**Issue by vinnyg0621** [Captain-Chaos/WorldPainter#388]
can you please add American English as an option for me please? I live in the U.S.A, and the only correct spelling for me here is "-ize". but this program uses "-ise". I hate British spellings!

**Comment by vinnyg0621** [comment]
mine might be similar to #357

**Comment by n8bar** [comment]
Not all Americans get hung up on spelling differences. Many of us are fine with British spellings and value understanding over regional preferences. But to each their own.

**Comment by vinnyg0621** [comment]
i just don't like them because they're not phonetic and they're hard to pronounce, but they're fine except when the "z" is replaced with an "s"

**Comment by Captain-Chaos** [comment]
When the application is internationalised (which may be a long time yet) it will also be easily possible to provide a US English translation.

**Comment by vinnyg0621** [comment]
> When the application is internationalised (which may be a long time yet) it will also be easily possible to provide a US English translation.

and the spelling "internationalised" is not acceptable in u.s. English either. the only correct spelling is "_internationalized_". but i would love to help with it!

**Comment by vinnyg0621** [comment]
@Captain-Chaos also your location also says Netherlands, so I think "-ise" and "-ize" are acceptable in your home country.

**Comment by Captain-Chaos** [comment]
> > When the application is internationalised (which may be a long time yet) it will also be easily possible to provide a US English translation.
> 
> and the spelling "internationalised" is not acceptable in u.s. English either. the only correct spelling is "_internationalized_". but i would love to help with it!

Why do _I_ have to use American spelling?!

The default language for WorldPainter is British English, since I am in Europe and that makes the most sense. You're going to have to find a way to deal with it.

I do plan to internationalise it at some point, but that is a lot of work and won't happen in the near future. There is already a Crowdin project. If you want to help, you could add a US English translation there, as long as you understand that for now the texts there are incomplete and it won't be used yet: https://crowdin.com/project/worldpainter

**Comment by vinnyg0621** [comment]
jeez, i didn't say you have to spell it "internationalize"
