### ISSUE TITLE
Custom Terrain Duping (BUG)

### ISSUE THREAD

**Issue by ErikSteiner** [Captain-Chaos/WorldPainter#39]
I recently discovered the functionality of the Custom Terrain (CT) Tab, it is very handy.
However I discovered a problem with the export and import function. If you are a lazy person like me,
you could come to the idea, that it would be a good trick to export your current CT, use the import option by clicking on the plus icon and rename the "new" CT to something else. You could then change any aspect of this "new" CT and do you thing.

The problem is, that the "new" CT is linked to the old CT:
I have one CT named Sandy Beach. I export it as Sandy Beach, use the import option and rename the "new" Sandy Beach to Beach. If I hover over the "new" CT, the mouse over will show me Beach and the old CT Sandy Beach, but if I right click on Sandy Beach and hit "Edit Custom Material", the Name changes to Beach.
More than that, every thing that has been changed in one CT, will be changed in the other one as well.

I hope this can be fixed and I would like to request an option to delete and to copy Custom Terrains in the Tab. I could then start to delete my duped CT's ^^

**EDIT:** I tested another thing. I imported a CT, then I made a copy of the .terrain file, renamed it to something different and tried to import that file. The result was, that even with another file name, the name of the CT was still the same and I got another duped Custom Terrain... 👎

**Comment by Captain-Chaos** [comment]
Yes, that is correct. Custom materials have persistent identities which even survive saving and loading, and only one custom material with the same identity can be loaded at the same time. However I can see that that might not be what you want in all circumstances.

Perhaps I should let go of that principle so that custom materials are always duplicated when saving and loading custom terrain types (but also various custom layers which use them). That might result in a lot of unwanted duplication of custom materials though.

**Comment by Captain-Chaos** [comment]
@ErikSteiner, could you file a new issue for the feature request? Issues should always be about one thing, that keeps things a lot easier to track and manage.
