### ISSUE TITLE
Random Intensity and rotation

### ISSUE THREAD

**Issue by Katrix** [Captain-Chaos/WorldPainter#48]
When working with a texture brush, it would be neat if you could add a toggle to randomize the intensity and rotation of the brush.

**Comment by Captain-Chaos** [comment]
I see what you mean, but I think it would be too complex to implement for a relatively niche feature (since you would have to have some way of indicating how much you want the intensity and rotation to vary), and it is pretty easy to do manually by using the middle mouse wheel with and without the Alt button while painting.
