### ISSUE TITLE
Snow layer does not work when using as ground cover layer.

### ISSUE THREAD

**Issue by ColonelOverspel** [Captain-Chaos/WorldPainter#70]
I wanted to cover some parts of my map with snow (78:0, the lowest snow layer there is) but after creating the brush this is what came out (I combined it with the second lowest snow layer 78:1 to see if that works, it does) [https://i.imgur.com/vn2FfPO.png](url). Am I doing something wrong?

**Comment by Captain-Chaos** [comment]
The red wool is a bug in WorldPainter which will be fixed shortly.

If you create a custom ground cover layer with 78:0 as the material you trigger WorldPainter's smooth deep snow layer support (see the latest change log), which varies the thickness of the snow. It doesn't look good if you just sprinkle a few blocks of it, and without knowing the exact settings you used on the ground cover layer I can't tell whether what I'm seeing is correct, but it probably is. Try painting a solid area of it.

This issue has convinced me however that using 78:0 to trigger smooth deep snow is not a good idea. I will change it to 78:7 in the next release, which you are unlikely to want to place as-is since it looks the same as the snow block (block ID 80).

The normal way of putting just a thin layer of snow in WorldPainter is to use the Frost layer. Normally that places smooth (varying thickness) snow, but if you don't want that you can turn that off in the Dimension Properties.

**Comment by Captain-Chaos** [comment]
Fixed in release 2.5.3

**Comment by Captain-Chaos** [comment]
Feel free to file a new issue if you think there is still a problem with this!

**Comment by ColonelOverspel** [comment]
Thanks a lot! I will try this with the new version again!

**Comment by ColonelOverspel** [comment]
By the way, the frost layer is awesome, but it also places ice, which is something I do not want.

**Comment by Captain-Chaos** [comment]
Another way to manage that could be to remove the Frost layer from all the water. You could do that easily in one step with the Global Operations tool.
