### ISSUE TITLE
Floating objects in mid-air

### ISSUE THREAD

**Issue by frogocomics** [Captain-Chaos/WorldPainter#72]
![2018-06-30_10 38 43](https://user-images.githubusercontent.com/10662167/42127676-db992b5c-7c51-11e8-9f2a-4144a582d7aa.png)
I can send you the world on request. The problem is, it is also a 1024 block high world. I'd also have to send you a custom coded converter that splits the world into slices.

**Comment by frogocomics** [comment]
![2018-06-30_10 41 03](https://user-images.githubusercontent.com/10662167/42127704-1ba7b8c6-7c52-11e8-915d-a693cc23aa15.png)

**Comment by Captain-Chaos** [comment]
Hmmm. Sorry, but I can't support custom coded converters. I'm not saying this isn't ultimately caused by a bug in WorldPainter, but I hope you can appreciate that it would take far too much of my time to have to debug problems related to third party tools. Especially since I'm working full-time again and will have much less time to spend on WorldPainter.

However if you can prove to me that this converter isn't causing the problem and WorldPainter is actually exporting the map wrong I'll look into it! Can you reproduce the problem with vanilla WorldPainter, or at least show that the error is already present in WorldPainter's export result?

**Comment by frogocomics** [comment]
I can show to you that the problem is not created by the converter and caused by WorldPainter itself.

**Comment by Captain-Chaos** [comment]
Great, in that case I will of course look into it. :) Just let me know how to reproduce the problem.

**Comment by Captain-Chaos** [comment]
That link doesn't work for me. It's probably easiest just to attach the file here.

And I need a way to reproduce this problem. Unfortunately I don't currently have the time to be experimenting, delving into the details of converters, etc.. The easiest for me would be a complete .world file that demonstrates the problem when I export it, without needing additional tools.

**Comment by frogocomics** [comment]
http://www.mediafire.com/file/4mwpvkv52cbv151/0001_Terraced_Mountains.world/file

**Comment by Captain-Chaos** [comment]
Thanks. I'll look into as soon as I have time.

**Comment by Captain-Chaos** [comment]
Well, this turned out to be a particularly nasty and hard to find bug. It would only affect non-standard height worlds, which almost no one uses. and only occur along region borders. Thanks for the heads up, I would have never known about this bug otherwise!

I just released version 2.5.5, in which this is fixed. Could you confirm that the problem is gone for you with that version?

**Comment by frogocomics** [comment]
The problem has been fixed. Thank you for fixing this, considering I am most likely the only person using non-standard heights at this point.

**Comment by Captain-Chaos** [comment]
That's entirely possible. :) But it's still important to find and fix fundamental bugs like this, who knows what other hard to find and/or fix problems they could otherwise cause in the future.
