### ISSUE TITLE
Provide Support for Numerical Ids Larger than 255

### ISSUE THREAD

**Issue by frogocomics** [Captain-Chaos/WorldPainter#97]
New 1.13 blocks, such as the stripped log have ids larger than 255. Alternatively, an option to use name_id in conjunction with numeric_id could also be implemented.

**Comment by Captain-Chaos** [comment]
Actually, 1.13 blocks do no have numerical IDs at all. As such the current production version of WorldPainter will never support them, but work is in progress on the next major release of WorldPainter, which will support Minecraft 1.13 with named blocks. You can check the alpha here: https://www.reddit.com/r/Worldpainter/comments/9aeixi/alpha_test_branch_released/

I'll close this issue since this is already under way.
