### ISSUE TITLE
UndoManager has a huge memory footprint, even if undo is disabled

### ISSUE THREAD

**Issue by InventivetalentDev** [Captain-Chaos/WorldPainter#98]
I've noticed the editor using quite a lot of memory when working on a large map. Eclipse Memory Analyzer showed that the largest objects are in the UndoManager class - but even after disabling undo via the preferences, that class still has a high memory consumption.  
![](https://yeleha.co/2GerkpA)
![](https://yeleha.co/2G9SXQn)
![](https://yeleha.co/2G6Wuiy)

Looks like the LinkedList in the UndoManager is the main issue, that being the `history` I assumed that would be empty if undo is disabled.  

Also seems like the memory usage doubles when loading another map: 
![](https://yeleha.co/2G7CcFF)

**Comment by Captain-Chaos** [comment]
There is always an UndoManager installed, even when undo is turned off, because WorldPainter needs to be able to roll back certain actions. For example, if you have combined layers, WorldPainter applies them to the world during an Export but then rolls those changes back again. UndoManager always contains references to the current data buffers, even if there is no undo data, so it will always be big. And lastly, the memory usage of the virtual machine doesn't tell you much, since it doesn't tell you how much of that is actually in use and not empty heap which might be relinquished at some point in the future. A better indicator is the memory usage meter in the toolbar at the bottom of the WorldPainter window.

Since I don't see an actual issue I'm going to close this, but if you think there really is a problem feel free to open a new issue with more details! If you have further technical questions it's probably best to ask those on the subreddit.
