### ISSUE TITLE
'Content is not allowed in Prolog' error when trying to export

### ISSUE THREAD

**Issue by SpacePiracy112** [Captain-Chaos/WorldPainter#99]
When I try to export I get the message
'Content is not allowed in Prolog'
https://pastebin.com/TMERHZz5

**Comment by Captain-Chaos** [comment]
Can you give me more details about the exact history of the world you're trying to export, and whether you made any changes to the export settings concerning a custom world type, generator options or superflat mode preset? Or better yet, attach the .world file?

**Comment by SpacePiracy112** [comment]
I was exporting it as a superflat world to avoid the lakes generated by populate, I just tried exporting it as a default world and it worked. My superflat string was as follows: 3;1*minecraft:bedrock,7*minecraft:dirt,1*minecraft:grass;2;decoration

**Comment by Captain-Chaos** [comment]
Ah yes. I'm afraid that in Minecraft 1.13 the superflat preset is no longer a simple string. It's now a complex NBT data structure. WorldPainter doesn't yet support configuring that data structure in an easy way. For Minecraft 1.13 WorldPainter now actually expects XML in the Superlfat mode preset field, which it will convert to NBT.

It works to leave it empty, which will result in the default Superflat preset. Another way to go until support for an easier way is added (which may be a while) is to import a Superflat world from Minecraft 1.13, and then inspect the contents of the Superflat mode preset on the Export screen to see what the XML looks like and trying to adapt that for your use.

Since this is not a really bug but just unfinished functionality in the alpha I'm going to close this issue, but don't hesitate to ask further questions or open a new issue if you think something is not working right.
